wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1668933122.42983
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 22
      - 23
      - 35
      4: 3.10.8
      5: 0.13.4
      8:
      - 3
      - 5
control_type:
  desc: null
  value: js
env_name:
  desc: null
  value: PandaReachEvadeObstacles-v3
eval_freq:
  desc: null
  value: 10000
gradient_steps:
  desc: null
  value: -1
joint_obstacle_observation:
  desc: null
  value: closest
learning_starts:
  desc: null
  value: 1000
max_ep_steps:
  desc: null
  value: 50
n_envs:
  desc: null
  value: 1
policy_type:
  desc: null
  value: MultiInputPolicy
render:
  desc: null
  value: false
replay_buffer:
  desc: null
  value: null
reward_thresholds:
  desc: null
  value:
  - -7
  - -7
reward_type:
  desc: null
  value: sparse
seed:
  desc: null
  value: 12
show_debug_labels:
  desc: null
  value: true
show_goal_space:
  desc: null
  value: true
stages:
  desc: null
  value:
  - 1
  - wall_parkour_1
total_timesteps:
  desc: null
  value: 400000
